apiVersion: v1
baseDomain: bankspb.ru

proxy:
  httpProxy: http://tiger.bspb.ru:8080
  httpsProxy: http://tiger.bspb.ru:8080
  noProxy: .bankspb.ru,10.67.51.0/24

metadata:
  name: okd

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMTkxZWM0NzU4ODE5NDFiN2E5ZWQ5MTg5MzgzMmU5YzQ6WDkwMUZMVlZWTzFTQ09YWjEyMDE4VEtFQkVES1FWTzdTUk1WVU5IUlJPTU1MVktVRE5KQ1Y0M01LUDMwQ1FUSg==","email":"grigoriy.shutov@glowbyteconsulting.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMTkxZWM0NzU4ODE5NDFiN2E5ZWQ5MTg5MzgzMmU5YzQ6WDkwMUZMVlZWTzFTQ09YWjEyMDE4VEtFQkVES1FWTzdTUk1WVU5IUlJPTU1MVktVRE5KQ1Y0M01LUDMwQ1FUSg==","email":"grigoriy.shutov@glowbyteconsulting.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTU2YjMyNDI5LWNiNzItNDEwOS1hMmQwLWZiNWQ3Yjg3ODZiMDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhaR1kwTUdJeE5EVTNORE0wTXpFeE9XTTJNekV5WXpBeFpHVmxORFkyTlNKOS5zNVh6YUhKbzRpSTczeE1XaXFyZjQzVEhZdzI4VGFHaVM3QWVBZTFnaFVRQUJWTG1EUjJHNDlZb2JDWUtwR28yUGZvY1ZnMXpZRFFLZ3VPX1hNNzhyQmY1NHJqLXZ1NUxVUXphZkc2VVo3TEJaclhuTjAxaU95VzJ0MTZWNW1COHhhZkUyTFo2cTBxNUs0MXVtOElRUkR1OU5jdE1DcmhzdVRFN21aWF94aUdRZldhczlTU1NpMUdZSEpjNlUzWjJvaWpIWFZTdjlCbU93T1dKVzJKbk9WOGZkSUtDTElVZF94aFpOSWQ5S2xxWVZfay1LZXloLWxKOVVvTXdBUXFkdUFPUi1pTlJTeG1Rc2ZjMmI5djRNNDV5UExBRHFIUDRmUFNQa29wRm82aUtWeWdsQWFFVFNSOW5ZZmREdWhSSV90RXFaQjRXZ1F5cFdHbkduM2dTUVFvem5JQWFKSmp0enY3dHEtS040Y0YtWG9scEZvQWN5YmUtQVVNOHVSU0d0M1A3bEtzS09LWFFaNlRhUnBpTjNGUUx5RG5PSzU2cXN6VGE4XzQtN2tuZDZDb0lMdHhDYU1EdEZWQ2l6RE5sLUdydXFjUFlUTEJta2NxRHBEMDlrMmpWVUpNSnJ3cWZaX3VfY3luNk5CbFpFM1ozb0JMdUowWm5zaVd3VUJyS2M4LW1FNU94bzZpSHYyNVZEMlhMR2hwb1AxV2psOWp1NktPNWtzNlBMbEhvclpnRnZRLTBaZG5rWjNJYjg2NlpCNjY0OWt4TE5jM3BHNUZSa1M2cTFuRS1wYWdJOUtiS01pSFAwcFcwWXNKQ3JhNXZnclJEM3JYaWZENUpCZml2RXJVZnBwN3BEWWV2US1NMmV2VUt6TmVGemF5QVd1dW1rNDVKR3dScVhKcw==","email":"grigoriy.shutov@glowbyteconsulting.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTU2YjMyNDI5LWNiNzItNDEwOS1hMmQwLWZiNWQ3Yjg3ODZiMDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhaR1kwTUdJeE5EVTNORE0wTXpFeE9XTTJNekV5WXpBeFpHVmxORFkyTlNKOS5zNVh6YUhKbzRpSTczeE1XaXFyZjQzVEhZdzI4VGFHaVM3QWVBZTFnaFVRQUJWTG1EUjJHNDlZb2JDWUtwR28yUGZvY1ZnMXpZRFFLZ3VPX1hNNzhyQmY1NHJqLXZ1NUxVUXphZkc2VVo3TEJaclhuTjAxaU95VzJ0MTZWNW1COHhhZkUyTFo2cTBxNUs0MXVtOElRUkR1OU5jdE1DcmhzdVRFN21aWF94aUdRZldhczlTU1NpMUdZSEpjNlUzWjJvaWpIWFZTdjlCbU93T1dKVzJKbk9WOGZkSUtDTElVZF94aFpOSWQ5S2xxWVZfay1LZXloLWxKOVVvTXdBUXFkdUFPUi1pTlJTeG1Rc2ZjMmI5djRNNDV5UExBRHFIUDRmUFNQa29wRm82aUtWeWdsQWFFVFNSOW5ZZmREdWhSSV90RXFaQjRXZ1F5cFdHbkduM2dTUVFvem5JQWFKSmp0enY3dHEtS040Y0YtWG9scEZvQWN5YmUtQVVNOHVSU0d0M1A3bEtzS09LWFFaNlRhUnBpTjNGUUx5RG5PSzU2cXN6VGE4XzQtN2tuZDZDb0lMdHhDYU1EdEZWQ2l6RE5sLUdydXFjUFlUTEJta2NxRHBEMDlrMmpWVUpNSnJ3cWZaX3VfY3luNk5CbFpFM1ozb0JMdUowWm5zaVd3VUJyS2M4LW1FNU94bzZpSHYyNVZEMlhMR2hwb1AxV2psOWp1NktPNWtzNlBMbEhvclpnRnZRLTBaZG5rWjNJYjg2NlpCNjY0OWt4TE5jM3BHNUZSa1M2cTFuRS1wYWdJOUtiS01pSFAwcFcwWXNKQ3JhNXZnclJEM3JYaWZENUpCZml2RXJVZnBwN3BEWWV2US1NMmV2VUt6TmVGemF5QVd1dW1rNDVKR3dScVhKcw==","email":"grigoriy.shutov@glowbyteconsulting.com"}}}'

sshKey: 'ssh-ed25519 AAAA...'   
